apiVersion: v1
kind: Secret
metadata:
  name: frontend
type: Opaque
data:
  secret_env: ZG9udF90ZWxsX2FueW9uZQo=
  secret_file: YXBpLmVuYWJsZWQ9dHJ1ZQphcGkua2V5PUlHTlc0VFcKcm9vdC51c2VybmFtZT1rb25hbWkKcm9vdC5wYXNzd29yZD1VVURETFJMUkJBQkFTCgo=
